export const productosDisponibles = [
  {
    id: "1",
    codigo: "FERT-001",
    nombre: "Fertilizante NPK 20-20-20",
    precio: 85.5,
    stock: 100,
    categoria: "Fertilizantes",
  },
  {
    id: "2",
    codigo: "FERT-002",
    nombre: "Urea Agrícola 46%",
    precio: 75.0,
    stock: 150,
    categoria: "Fertilizantes",
  },
  {
    id: "3",
    codigo: "PEST-001",
    nombre: "Insecticida Orgánico",
    precio: 45.9,
    stock: 80,
    categoria: "Pesticidas",
  },
  {
    id: "4",
    codigo: "PEST-002",
    nombre: "Fungicida Sistémico",
    precio: 65.3,
    stock: 60,
    categoria: "Pesticidas",
  },
  {
    id: "5",
    codigo: "SEM-001",
    nombre: "Semillas de Maíz Híbrido",
    precio: 120.0,
    stock: 50,
    categoria: "Semillas",
  },
  {
    id: "6",
    codigo: "SEM-002",
    nombre: "Semillas de Arroz",
    precio: 95.5,
    stock: 70,
    categoria: "Semillas",
  },
  {
    id: "7",
    codigo: "HERR-001",
    nombre: "OWNER 380 WG CAJ. X 1 KG. (10 SOB. X 100G).",
    precio: 35.0,
    stock: 40,
    categoria: "Herramientas",
  },
  {
    id: "8",
    codigo: "HERR-002",
    nombre: "Aspersor de Riego",
    precio: 28.75,
    stock: 55,
    categoria: "Herramientas",
  },
  {
    id: "9",
    codigo: "FERT-003",
    nombre: "Abono Orgánico",
    precio: 55.2,
    stock: 90,
    categoria: "Fertilizantes",
  },
  {
    id: "10",
    codigo: "PEST-003",
    nombre: "Herbicida Selectivo",
    precio: 72.4,
    stock: 45,
    categoria: "Pesticidas",
  },
]
